#!/bin/sh

sudo xbps-install -Syu nerd-fonts emacs-gtk3 neovim p7zip \
  git curl wget lazygit keepassxc xclip font-iosevka \
  gcc make libX11-devel libXcursor-devel ripgrep gnupg \
  libXrandr-devel libXinerama-devel libXi-devel mupdf \
  galculator xfce4-screenshooter
