#!/bin/sh

echo "Configurando setup..." && \
  sudo apt update && \
  sudo apt install extrepo -y && \
  sudo extrepo enable librewolf && \
  sudo apt update && \
  sudo apt install -y \
  librewolf sway swaybg \
  swayidle grim slurp \
  wf-recorder pulsemixer \
  cmus cava playerctl tofi \
  foot ranger wl-clipboard \
  mpv imv htop keepassxc \
  qpwgraph scdoc gcc make \
  wine xwayland git wget curl \
  brightnessctl fonts-jetbrains-mono \
  unzip imagemagick pandoc mupdf bc

mkdir ~/.fonts

wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

unzip JetBrainsMono.zip -d ~/.fonts

sudo fc-cache -frv

cp -r .bashrc ~/
cp -r .config ~/
cp -r .local ~/
