# For complete documentation of this file, please see Geany's main documentation
[styling]
# Edit these in the colorscheme .conf file instead
default=default
commentblock=comment
commentline=comment_line
commentblockdoc=comment_doc
commentlinedoc=comment_doc
number=number_1
word=keyword_1
word2=keyword_2
word3=keyword_3
word4=type
string=string_1
stringraw=string_2
character=character
bytestring=string_1
bytestringraw=string_2
bytecharacter=character
operator=operator
identifier=identifier_1
lexerror=error

[keywords]
# all items must be in one line
primary=export defer def insert delete append as break const continue else enum false fn for if let match return sizeof switch assert len free static struct true type typeof use yield
secondary=bool f32 f64 i128 i16 i32 i64 i8 str u128 u16 u32 u64 u8 void opaque rune size null nullable
tertiary=@symbol

[lexer_properties]
styling.within.preprocessor=1
lexer.cpp.track.preprocessor=0

[settings]
lexer_filetype=Rust
# default extension used when saving files
extension=ha

# MIME type
# mime_type=text/x-csrc

# single comments, like # in this file
comment_single=//
# multiline comments
# comment_open=/*
# comment_close=*/

# set to false if a comment character/string should start at column 0 of a line, true uses any
# indentation of the line, e.g. setting to true causes the following on pressing CTRL+d
# 		#command_example();
# setting to false would generate this
# #		command_example();
# This setting works only for single line comments
comment_use_indent=true

# context action command (please see Geany's main documentation for details)
context_action_cmd=

[indentation]
width=8
# 0 is spaces, 1 is tabs, 2 is tab & spaces
type=1

[build-menu]
FT_00_LB=Compile
FT_00_CM=hare build -o "%e" "%f"
FT_00_WD=
EX_00_LB=Run
EX_00_CM=hare run "%f"
EX_00_WD=
error_regex=  --> (.+):([0-9]+):([0-9]+)
